using Microsoft.EntityFrameworkCore;
using SGED.Objects.Models.Entities;

namespace SGED.Context.Builders
{
    public class TipoLogradouroBuilder
    {
        public static void Build(ModelBuilder modelBuilder)
        {
            // Builder
            modelBuilder.Entity<TipoLogradouro>().HasKey(tl => tl.Id);
            modelBuilder.Entity<TipoLogradouro>().Property(tl => tl.CodigoInformativo).HasMaxLength(3).IsRequired();
            modelBuilder.Entity<TipoLogradouro>().Property(tl => tl.Descricao).HasMaxLength(35).IsRequired();


            // Inserções
            modelBuilder.Entity<TipoLogradouro>().HasData(
                new TipoLogradouro { Id = 1, CodigoInformativo = "A", Descricao = "Área" },
                new TipoLogradouro { Id = 2, CodigoInformativo = "AC", Descricao = "Acesso" },
                new TipoLogradouro { Id = 3, CodigoInformativo = "ACA", Descricao = "Acampamento" },
                new TipoLogradouro { Id = 4, CodigoInformativo = "ACL", Descricao = "Acesso Local" },
                new TipoLogradouro { Id = 5, CodigoInformativo = "AD", Descricao = "Adro" },
                new TipoLogradouro { Id = 6, CodigoInformativo = "AE", Descricao = "Área Especial" },
                new TipoLogradouro { Id = 7, CodigoInformativo = "AER", Descricao = "Aeroporto" },
                new TipoLogradouro { Id = 8, CodigoInformativo = "AL", Descricao = "Alameda" },
                new TipoLogradouro { Id = 9, CodigoInformativo = "AMD", Descricao = "Avenida Marginal Direita" },
                new TipoLogradouro { Id = 10, CodigoInformativo = "AME", Descricao = "Avenida Marginal Esquerda" },
                new TipoLogradouro { Id = 11, CodigoInformativo = "AN", Descricao = "Anel Viário" },
                new TipoLogradouro { Id = 12, CodigoInformativo = "ANT", Descricao = "Antiga Estrada" },
                new TipoLogradouro { Id = 13, CodigoInformativo = "ART", Descricao = "Artéria" },
                new TipoLogradouro { Id = 14, CodigoInformativo = "AT", Descricao = "Alto" },
                new TipoLogradouro { Id = 15, CodigoInformativo = "ATL", Descricao = "Atalho" },
                new TipoLogradouro { Id = 16, CodigoInformativo = "A V", Descricao = "Área Verde" },
                new TipoLogradouro { Id = 17, CodigoInformativo = "AV", Descricao = "Avenida" },
                new TipoLogradouro { Id = 18, CodigoInformativo = "AV", Descricao = "Avenida" },
                new TipoLogradouro { Id = 19, CodigoInformativo = "AVC", Descricao = "Avenida do Contorno" },
                new TipoLogradouro { Id = 20, CodigoInformativo = "AVM", Descricao = "Avenida Marginal" },
                new TipoLogradouro { Id = 21, CodigoInformativo = "AVV", Descricao = "Avenida Velha" },
                new TipoLogradouro { Id = 22, CodigoInformativo = "BAL", Descricao = "Balneário" },
                new TipoLogradouro { Id = 23, CodigoInformativo = "BC", Descricao = "Beco" },
                new TipoLogradouro { Id = 24, CodigoInformativo = "BCO", Descricao = "Buraco" },
                new TipoLogradouro { Id = 25, CodigoInformativo = "BEL", Descricao = "Belvedere" },
                new TipoLogradouro { Id = 26, CodigoInformativo = "BL", Descricao = "Bloco" },
                new TipoLogradouro { Id = 27, CodigoInformativo = "BLO", Descricao = "Balão" },
                new TipoLogradouro { Id = 28, CodigoInformativo = "BLS", Descricao = "Blocos" },
                new TipoLogradouro { Id = 29, CodigoInformativo = "BLV", Descricao = "Bulevar" },
                new TipoLogradouro { Id = 30, CodigoInformativo = "BSQ", Descricao = "Bosque" },
                new TipoLogradouro { Id = 31, CodigoInformativo = "BVD", Descricao = "Boulevard" },
                new TipoLogradouro { Id = 32, CodigoInformativo = "BX", Descricao = "Baixa" },
                new TipoLogradouro { Id = 33, CodigoInformativo = "C", Descricao = "Cais" },
                new TipoLogradouro { Id = 34, CodigoInformativo = "CAL", Descricao = "Calçada" },
                new TipoLogradouro { Id = 35, CodigoInformativo = "CAM", Descricao = "Caminho" },
                new TipoLogradouro { Id = 36, CodigoInformativo = "CAN", Descricao = "Canal" },
                new TipoLogradouro { Id = 37, CodigoInformativo = "CH", Descricao = "Chácara" },
                new TipoLogradouro { Id = 38, CodigoInformativo = "CHA", Descricao = "Chapadão" },
                new TipoLogradouro { Id = 39, CodigoInformativo = "CIC", Descricao = "Ciclovia" },
                new TipoLogradouro { Id = 40, CodigoInformativo = "CIR", Descricao = "Circular" },
                new TipoLogradouro { Id = 41, CodigoInformativo = "CJ", Descricao = "Conjunto" },
                new TipoLogradouro { Id = 42, CodigoInformativo = "CJM", Descricao = "Conjunto Multirão" },
                new TipoLogradouro { Id = 43, CodigoInformativo = "CMP", Descricao = "Complexo Viário" },
                new TipoLogradouro { Id = 44, CodigoInformativo = "COL", Descricao = "Colônia" },
                new TipoLogradouro { Id = 45, CodigoInformativo = "COM", Descricao = "Comunidade" },
                new TipoLogradouro { Id = 46, CodigoInformativo = "CON", Descricao = "Condomínio" },
                new TipoLogradouro { Id = 47, CodigoInformativo = "COR", Descricao = "Corredor" },
                new TipoLogradouro { Id = 48, CodigoInformativo = "CPO", Descricao = "Campo" },
                new TipoLogradouro { Id = 49, CodigoInformativo = "CRG", Descricao = "Córrego" },
                new TipoLogradouro { Id = 50, CodigoInformativo = "CTN", Descricao = "Contorno" },
                new TipoLogradouro { Id = 51, CodigoInformativo = "DSC", Descricao = "Descida" },
                new TipoLogradouro { Id = 52, CodigoInformativo = "DSV", Descricao = "Desvio" },
                new TipoLogradouro { Id = 53, CodigoInformativo = "DT", Descricao = "Distrito" },
                new TipoLogradouro { Id = 54, CodigoInformativo = "EB", Descricao = "Entre Bloco" },
                new TipoLogradouro { Id = 55, CodigoInformativo = "EIM", Descricao = "Estrada Intermunicipal" },
                new TipoLogradouro { Id = 56, CodigoInformativo = "ENS", Descricao = "Enseada" },
                new TipoLogradouro { Id = 57, CodigoInformativo = "ENT", Descricao = "Entrada Particular" },
                new TipoLogradouro { Id = 58, CodigoInformativo = "EQ", Descricao = "Entre Quadra" },
                new TipoLogradouro { Id = 59, CodigoInformativo = "ESC", Descricao = "Escada" },
                new TipoLogradouro { Id = 60, CodigoInformativo = "ESD", Descricao = "Escadaria" },
                new TipoLogradouro { Id = 61, CodigoInformativo = "ESE", Descricao = "Estrada Estadual" },
                new TipoLogradouro { Id = 62, CodigoInformativo = "ESI", Descricao = "Estrada Vicinal" },
                new TipoLogradouro { Id = 63, CodigoInformativo = "ESL", Descricao = "Estrada de Ligação" },
                new TipoLogradouro { Id = 64, CodigoInformativo = "ESM", Descricao = "Estrada Municipal" },
                new TipoLogradouro { Id = 65, CodigoInformativo = "ESP", Descricao = "Esplanada" },
                new TipoLogradouro { Id = 66, CodigoInformativo = "ESS", Descricao = "Estrada de Servidão" },
                new TipoLogradouro { Id = 67, CodigoInformativo = "EST", Descricao = "Estrada" },
                new TipoLogradouro { Id = 68, CodigoInformativo = "ESV", Descricao = "Estrada Velha" },
                new TipoLogradouro { Id = 69, CodigoInformativo = "ETA", Descricao = "Estrada Antiga" },
                new TipoLogradouro { Id = 70, CodigoInformativo = "ETC", Descricao = "Estação" },
                new TipoLogradouro { Id = 71, CodigoInformativo = "ETD", Descricao = "Estádio" },
                new TipoLogradouro { Id = 72, CodigoInformativo = "ETN", Descricao = "Estância" },
                new TipoLogradouro { Id = 73, CodigoInformativo = "ETP", Descricao = "Estrada Particular" },
                new TipoLogradouro { Id = 74, CodigoInformativo = "ETT", Descricao = "Estacionamento" },
                new TipoLogradouro { Id = 75, CodigoInformativo = "EVA", Descricao = "Evangélica" },
                new TipoLogradouro { Id = 76, CodigoInformativo = "EVD", Descricao = "Elevada" },
                new TipoLogradouro { Id = 77, CodigoInformativo = "EX", Descricao = "Eixo Industrial" },
                new TipoLogradouro { Id = 78, CodigoInformativo = "FAV", Descricao = "Favela" },
                new TipoLogradouro { Id = 79, CodigoInformativo = "FAZ", Descricao = "Fazenda" },
                new TipoLogradouro { Id = 80, CodigoInformativo = "FER", Descricao = "Ferrovia" },
                new TipoLogradouro { Id = 81, CodigoInformativo = "FNT", Descricao = "Fonte" },
                new TipoLogradouro { Id = 82, CodigoInformativo = "FRA", Descricao = "Feira" },
                new TipoLogradouro { Id = 83, CodigoInformativo = "FTE", Descricao = "Forte" },
                new TipoLogradouro { Id = 84, CodigoInformativo = "GAL", Descricao = "Galeria" },
                new TipoLogradouro { Id = 85, CodigoInformativo = "GJA", Descricao = "Granja" },
                new TipoLogradouro { Id = 86, CodigoInformativo = "HAB", Descricao = "Núcleo Habitacional" },
                new TipoLogradouro { Id = 87, CodigoInformativo = "IA", Descricao = "Ilha" },
                new TipoLogradouro { Id = 88, CodigoInformativo = "IND", Descricao = "Indeterminado" },
                new TipoLogradouro { Id = 89, CodigoInformativo = "IOA", Descricao = "Ilhota" },
                new TipoLogradouro { Id = 90, CodigoInformativo = "JD", Descricao = "Jardim" },
                new TipoLogradouro { Id = 91, CodigoInformativo = "JDE", Descricao = "Jardinete" },
                new TipoLogradouro { Id = 92, CodigoInformativo = "LD", Descricao = "Ladeira" },
                new TipoLogradouro { Id = 93, CodigoInformativo = "LGA", Descricao = "Lagoa" },
                new TipoLogradouro { Id = 94, CodigoInformativo = "LGO", Descricao = "Lago" },
                new TipoLogradouro { Id = 95, CodigoInformativo = "LOT", Descricao = "Loteamento" },
                new TipoLogradouro { Id = 96, CodigoInformativo = "LRG", Descricao = "Largo" },
                new TipoLogradouro { Id = 97, CodigoInformativo = "LT", Descricao = "Lote" },
                new TipoLogradouro { Id = 98, CodigoInformativo = "MER", Descricao = "Mercado" },
                new TipoLogradouro { Id = 99, CodigoInformativo = "MNA", Descricao = "Marina" },
                new TipoLogradouro { Id = 100, CodigoInformativo = "MOD", Descricao = "Modulo" },
                new TipoLogradouro { Id = 101, CodigoInformativo = "MRG", Descricao = "Projeção" },
                new TipoLogradouro { Id = 102, CodigoInformativo = "MRO", Descricao = "Morro" },
                new TipoLogradouro { Id = 103, CodigoInformativo = "MTE", Descricao = "Monte" },
                new TipoLogradouro { Id = 104, CodigoInformativo = "NUC", Descricao = "Núcleo" },
                new TipoLogradouro { Id = 105, CodigoInformativo = "NUR", Descricao = "Núcleo Rural" },
                new TipoLogradouro { Id = 106, CodigoInformativo = "OUT", Descricao = "Outeiro" },
                new TipoLogradouro { Id = 107, CodigoInformativo = "PAR", Descricao = "Paralela" },
                new TipoLogradouro { Id = 108, CodigoInformativo = "PAS", Descricao = "Passeio" },
                new TipoLogradouro { Id = 109, CodigoInformativo = "PAT", Descricao = "Pátio" },
                new TipoLogradouro { Id = 110, CodigoInformativo = "PC", Descricao = "Praça" },
                new TipoLogradouro { Id = 111, CodigoInformativo = "PCE", Descricao = "Praça de Esportes" },
                new TipoLogradouro { Id = 112, CodigoInformativo = "PDA", Descricao = "Parada" },
                new TipoLogradouro { Id = 113, CodigoInformativo = "PDO", Descricao = "Paradouro" },
                new TipoLogradouro { Id = 114, CodigoInformativo = "PNT", Descricao = "Ponta" },
                new TipoLogradouro { Id = 115, CodigoInformativo = "PR", Descricao = "Praia" },
                new TipoLogradouro { Id = 116, CodigoInformativo = "PRL", Descricao = "Prolongamento" },
                new TipoLogradouro { Id = 117, CodigoInformativo = "PRM", Descricao = "Parque Municipal" },
                new TipoLogradouro { Id = 118, CodigoInformativo = "PRQ", Descricao = "Parque" },
                new TipoLogradouro { Id = 119, CodigoInformativo = "PRR", Descricao = "Parque Residencial" },
                new TipoLogradouro { Id = 120, CodigoInformativo = "PSA", Descricao = "Passarela" },
                new TipoLogradouro { Id = 121, CodigoInformativo = "PSG", Descricao = "Passagem" },
                new TipoLogradouro { Id = 122, CodigoInformativo = "PSP", Descricao = "Passagem de Pedestre" },
                new TipoLogradouro { Id = 123, CodigoInformativo = "PSS", Descricao = "Passagem Subterrânea" },
                new TipoLogradouro { Id = 124, CodigoInformativo = "PTE", Descricao = "Ponte" },
                new TipoLogradouro { Id = 125, CodigoInformativo = "PTO", Descricao = "Porto" },
                new TipoLogradouro { Id = 126, CodigoInformativo = "Q", Descricao = "Quadra" },
                new TipoLogradouro { Id = 127, CodigoInformativo = "QTA", Descricao = "Quinta" },
                new TipoLogradouro { Id = 128, CodigoInformativo = "QTS", Descricao = "Quintas" },
                new TipoLogradouro { Id = 129, CodigoInformativo = "R", Descricao = "Rua" },
                new TipoLogradouro { Id = 130, CodigoInformativo = "R I", Descricao = "Rua Integração" },
                new TipoLogradouro { Id = 131, CodigoInformativo = "R L", Descricao = "Rua de Ligação" },
                new TipoLogradouro { Id = 132, CodigoInformativo = "R P", Descricao = "Rua Particular" },
                new TipoLogradouro { Id = 133, CodigoInformativo = "R V", Descricao = "Rua Velha" },
                new TipoLogradouro { Id = 134, CodigoInformativo = "RAM", Descricao = "Ramal" },
                new TipoLogradouro { Id = 135, CodigoInformativo = "RCR", Descricao = "Recreio" },
                new TipoLogradouro { Id = 136, CodigoInformativo = "REC", Descricao = "Recanto" },
                new TipoLogradouro { Id = 137, CodigoInformativo = "RER", Descricao = "Retiro" },
                new TipoLogradouro { Id = 138, CodigoInformativo = "RES", Descricao = "Residencial" },
                new TipoLogradouro { Id = 139, CodigoInformativo = "RET", Descricao = "Reta" },
                new TipoLogradouro { Id = 140, CodigoInformativo = "RLA", Descricao = "Ruela" },
                new TipoLogradouro { Id = 141, CodigoInformativo = "RMP", Descricao = "Rampa" },
                new TipoLogradouro { Id = 142, CodigoInformativo = "ROA", Descricao = "Rodo Anel" },
                new TipoLogradouro { Id = 143, CodigoInformativo = "ROD", Descricao = "Rodovia" },
                new TipoLogradouro { Id = 144, CodigoInformativo = "ROT", Descricao = "Rotula" },
                new TipoLogradouro { Id = 145, CodigoInformativo = "RPE", Descricao = "Rua de Pedestre" },
                new TipoLogradouro { Id = 146, CodigoInformativo = "RPR", Descricao = "Margem" },
                new TipoLogradouro { Id = 147, CodigoInformativo = "RTN", Descricao = "Retorno" },
                new TipoLogradouro { Id = 148, CodigoInformativo = "RTT", Descricao = "Rotatória" },
                new TipoLogradouro { Id = 149, CodigoInformativo = "SEG", Descricao = "Segunda Avenida" },
                new TipoLogradouro { Id = 150, CodigoInformativo = "SIT", Descricao = "Sitío" },
                new TipoLogradouro { Id = 151, CodigoInformativo = "SRV", Descricao = "Servidão" },
                new TipoLogradouro { Id = 152, CodigoInformativo = "ST", Descricao = "Setor" },
                new TipoLogradouro { Id = 153, CodigoInformativo = "SUB", Descricao = "Subida" },
                new TipoLogradouro { Id = 154, CodigoInformativo = "TCH", Descricao = "Trincheira" },
                new TipoLogradouro { Id = 155, CodigoInformativo = "TER", Descricao = "Terminal" },
                new TipoLogradouro { Id = 156, CodigoInformativo = "TR", Descricao = "Trecho" },
                new TipoLogradouro { Id = 157, CodigoInformativo = "TRV", Descricao = "Trevo" },
                new TipoLogradouro { Id = 158, CodigoInformativo = "TUN", Descricao = "Túnel" },
                new TipoLogradouro { Id = 159, CodigoInformativo = "TV", Descricao = "Travessa" },
                new TipoLogradouro { Id = 160, CodigoInformativo = "TVP", Descricao = "Travessa Particular" },
                new TipoLogradouro { Id = 161, CodigoInformativo = "TVV", Descricao = "Travessa Velha" },
                new TipoLogradouro { Id = 162, CodigoInformativo = "UNI", Descricao = "Unidade" },
                new TipoLogradouro { Id = 163, CodigoInformativo = "V", Descricao = "Via" },
                new TipoLogradouro { Id = 164, CodigoInformativo = "V C", Descricao = "Via Coletora" },
                new TipoLogradouro { Id = 165, CodigoInformativo = "V L", Descricao = "Via Local" },
                new TipoLogradouro { Id = 166, CodigoInformativo = "VAC", Descricao = "Via de Acesso" },
                new TipoLogradouro { Id = 167, CodigoInformativo = "VAL", Descricao = "Vala" },
                new TipoLogradouro { Id = 168, CodigoInformativo = "VCO", Descricao = "Vila Costeira" },
                new TipoLogradouro { Id = 169, CodigoInformativo = "VD", Descricao = "Viaduto" },
                new TipoLogradouro { Id = 170, CodigoInformativo = "V-E", Descricao = "Via Expressa" },
                new TipoLogradouro { Id = 171, CodigoInformativo = "VEV", Descricao = "Via Elevado" },
                new TipoLogradouro { Id = 173, CodigoInformativo = "VL", Descricao = "Vila" },
                new TipoLogradouro { Id = 174, CodigoInformativo = "VLA", Descricao = "Viela" },
                new TipoLogradouro { Id = 175, CodigoInformativo = "VLE", Descricao = "Vale" },
                new TipoLogradouro { Id = 176, CodigoInformativo = "VLT", Descricao = "Vila Litorânea" },
                new TipoLogradouro { Id = 177, CodigoInformativo = "VPE", Descricao = "Via de Pedestre" },
                new TipoLogradouro { Id = 178, CodigoInformativo = "VRT", Descricao = "Variante" },
                new TipoLogradouro { Id = 179, CodigoInformativo = "ZIG", Descricao = "Zigue-zague" }
            );
        }
    }

}
